### ISSUE TITLE
Out of date documentation? SVGElement.getStyle()

### ISSUE THREAD

**Issue by frankvdh** [blackears/svgSalamander#109]
Documentation at https://github.com/blackears/svgSalamander/blob/master/doc/usingSvgSalamander.md includes the following example to get the style of an SVGElement, but it doesn't work.... getStyle does not accept a String parameter. Uing v1.1.4 of SVG Salamander

```
StyleAttribute attrib = new StyleAttribute(); 
svgElement.getStyle("fill", attrib); 
double value = attrib.getDoubleValue(); 
```

**Comment by frankvdh** [comment]
After perusing the source code, it seems the correct usage is:

```
                StyleAttribute style = new StyleAttribute();
                style.setName("fill");
                svgElement.getStyle(style);
                double value = style.getDoubleValue(); 
```

**Comment by blackears** [comment]
I've updated the docs.  Thanks.
