### ISSUE TITLE
Intermittent Nullpointer exception 

### ISSUE THREAD

**Issue by davidekholm** [blackears/svgSalamander#24]
Hi. Our users sometimes report nullpointer exceptions in svgsalamander. It seems intermittent and I cannot reproduce it myself. Here's the stack trace:

> java.lang.NullPointerException
> at com.kitfox.svg.SVGDiagram.render(SVGDiagram.java:105)
> at com.kitfox.svg.app.beans.SVGIcon.paintIcon(SVGIcon.java:280)
> at com.kitfox.svg.app.beans.SVGIcon.paintIcon(SVGIcon.java:171)
> at se.datadosen.component.DeferredSVGIcon.paintIcon(DeferredSVGIcon.java:84)
> at com.kitfox.svg.app.beans.SVGIcon.getImage(SVGIcon.java:113)
> at se.datadosen.component.JPlainButton.brighten(JPlainButton.java:157)
> at se.datadosen.component.JPlainButton.setIcon(JPlainButton.java:137)
> at javax.swing.AbstractButton.init(AbstractButton.java:2172)
> at javax.swing.JButton.<init>(JButton.java:137)
> at javax.swing.JButton.<init>(JButton.java:100)
> at se.datadosen.component.JPlainButton.<init>(JPlainButton.java:73)
> at se.datadosen.component.JNotification.<init>(JNotification.java:82)
> at se.datadosen.jalbum.TipOfTheDay.showInBackground(TipOfTheDay.java:63)
> at se.datadosen.jalbum.JPublishWizard$PublishStep.doAfterUploadAlbum(JPublishWizard.java:2077)
> at se.datadosen.jalbum.JPublishWizard$PublishStep.access$1400(JPublishWizard.java:747)
> at se.datadosen.jalbum.JPublishWizard$PublishStep$20.run(JPublishWizard.java:1928)

**Comment by blackears** [comment]
You seem to be using an  out of date version of the code.  Please download the latest version and try that,

**Comment by davidekholm** [comment]
Thanks. Will update to the current one.
