### ISSUE TITLE
Possible typo in the code

### ISSUE THREAD

**Issue by mgarin** [blackears/svgSalamander#49]
I was checking the source code of `SVGUniverse` and found this line:
https://github.com/blackears/svgSalamander/blob/master/svg-core/src/main/java/com/kitfox/svg/SVGUniverse.java#L393

Was it supposed to be:
```java
url = SVGUniverse.class.getResource( xmlBase.getPath() );
```
Instead of the:
```java
url = SVGUniverse.class.getResource("xmlBase.getPath()");
```
by any chance?

**Comment by blackears** [comment]
Yes, that looks like bug.  Thanks for the catch.
