### ISSUE TITLE
mouse click listener on SVGElement?

### ISSUE THREAD

**Issue by robertaecosta** [blackears/svgSalamander#50]
Hi,

We have been using SVG Salamander for a while and it works great, thanks a lot!
However, I have been requested to upgrade our SVG Panel to respond to mouse click on some elements. 
Would that be possible with SVG Salamander? 

This is probably not the proper channel to be asking this kind of support, sorry about that.. if there is such a channel, could you please redirect me?

**Comment by blackears** [comment]
This is probably the most appropriate place for now. This project doesn't get much traffic.

SVG Salamander does have support for picking.  Just implement a method to detect mouse clicks on your panel and then call one of the SVGDiagram.pick() methods to get a list of all svg shapes in your pick area.

**Comment by robertaecosta** [comment]
I'll try that, thanks a lot
