### ISSUE TITLE
no way to replace content of Text element

### ISSUE THREAD

**Issue by medovina** [blackears/svgSalamander#69]
From looking at the svgSalamander source code (i.e. Text.java), I can't see any way that an application can replace the content of a Text element with a new string.  There are public methods appendText() and appendTspan() that can __append__ to the content.  But it would additionally be very useful to be able to replace the content altogether.

**Comment by blackears** [comment]
I've added a clearContent() method to Text so that you can remove all text data from it.  That should allow you to set your text data.

**Comment by medovina** [comment]
Great, thanks for the quick fix!
