### ISSUE TITLE
StyleAttributes resolves URI incorrectly when running on module path

### ISSUE THREAD

**Issue by weisJ** [blackears/svgSalamander#76]
Note that this happens when running on the module path due to a somewhat different code path when calling `Class#getResource`. The issue in particular is the following:
Assuming that we are packaged in a jar (haven't testes it for non packaged content yet but I assume the same issue occurs)
````java
 URI base = SomeClass.class.getResource("someResource.svg").toURI();
 System.out.println(base);
// This prints: jar:file///[path to jar]![package path of SomeClass]/someResource.svg
// On the classpath it is: jar:file/[path to jar]![package path of SomeClass]/someResource.svg
// => The amount of slashes is differen.

// The following code is abridged from StyleAttribute#getURIValue(URI)
String fragment = "#fragment";

//[scheme:]scheme-specific-part[#fragment]
URI uriFrag = new URI(fragment);
if (uriFrag.isAbsolute()) { // ... Unrelevant branch }

URI relBase = new URI(null, base.getSchemeSpecificPart(), null);
System.out.println("RelBase: " + relBase);
URI relUri;
if (relBase.isOpaque()) {
   // ... Unrelevant branch
} else {
    relUri = relBase.resolve(uriFrag);
}
System.out.println("relUri " + relUri);
// Here relUri = jar:file/[path to jar]![package path of SomeClass]/someResource.svg#fragment
// Now with one slash!
return new URI(base.getScheme() + ":" + relUri)
````
This causes the `SVGDiagram` for all files to be loaded twice if the svg uses `url()` attributes.
Once when loading the svg i.e. `SVGUniverse#load` and then a second time in `SVGUniverse#getElement` called with
the now modified xml base from the code above.
In `SVGUniverse#getElement` only `xmlBase.getSchemeSpecificPart()` is relevant which now is different that when loading the first time.
Besides the increased memory usage this is painful in particular when modifying the xml graph at runtime. Any modifications won't be mirrored when painting as the duplicated diagram is used there.

~~Note that the problematic call is `relBase.resolve(uriFrag)`, which looses the slashes in `URI::resolvePath`.~~
Actually I'm not quite certain this is the problematic line. Moreover I am somewhat unsure why the two branches in `if (relbase.isQpaque())` are different. The line in the true branch does preserve the uri structure correctly.
````java
relUri = new URI(null, base.getSchemeSpecificPart(), uriFrag.getFragment());
````
I'm really not experienced with the whole `URI` situation. Is there a scenario, where `relBase` can actually be `opaque` the way it is defined?

**Comment by blackears** [comment]
I've made a change to the source.  The updated code should look for the triple slash and replace it.

**Comment by blackears** [comment]
Closing this issue.  Please reopen if you continue to have problems.
