### ISSUE TITLE
Image with base64 data not rendered

### ISSUE THREAD

**Issue by VISTALL** [blackears/svgSalamander#84]
Hello.

Example svg 

https://raw.githubusercontent.com/JetBrains/intellij-plugins/master/protobuf/resources/META-INF/pluginIcon.svg

Actual result, exception:

```
java.io.FileNotFoundException: https://raw.githubusercontent.com/JetBrains/intellij-plugins/master/protobuf/resources/META-INF/null
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
```

Expected result - render image from base64.

Thanks.

**Comment by blackears** [comment]
The problem is that you've set the 'stroke' attribute in all of the tags to be "null"  (ie, the text string "null", not a null value).  Is this valid SVG syntax?

**Comment by VISTALL** [comment]
Oh. It's not my icon. Maybe it's a bug. Chrome and GitHub show in different ways it (https://github.com/JetBrains/intellij-plugins/blob/master/protobuf/resources/META-INF/pluginIcon.svg)

I'm not sure about  it

**Comment by VISTALL** [comment]
Looks like you are right. Even Illustrator failed to render :) My bad. I  think we can close this issue
