### ISSUE TITLE
Parsing a single transform with capitalized e notation is not working

### ISSUE THREAD

**Issue by nfohrer** [blackears/svgSalamander#85]
Hello,

Would it be possible to allow parsing a single transform when using the capitalized _e notation_?

https://github.com/blackears/svgSalamander/blob/d314d1d1cac8eeed2f66c3b91a264f4d9a1cebf0/svg-core/src/main/java/com/kitfox/svg/SVGElement.java#L733

With this example:
```
<svg xmlns="http://www.w3.org/2000/svg">  
   <g transform="matrix(2.64845E-014 -1 1 2.64845E-014 127.203 1119.35)">
    <text x="800" y="500">Hello world!</text>
   </g>
</svg>
```

The results are as follows:
> function = "matrix"
> termList = [2.64845, E, -014, -1, 1, 2.64845, E, -014, 127.203, 1119.35]

And the corresponding text is not rendered.

Thank you.

**Comment by blackears** [comment]
The library should handle capital Es now.

**Comment by nfohrer** [comment]
Thank you.
