### ISSUE TITLE
New official release version

### ISSUE THREAD

**Issue by ssenegas** [blackears/svgSalamander#86]
Hello there,

The latest official release available here is [1.1.2 from 08 Aug 2018](https://github.com/blackears/svgSalamander/releases/tag/v1.1.2).

It would be awesome to release a new version that includes the latest fixes closed those days?

Kind regards,
Sébastien

**Comment by ssenegas** [comment]
sorry for being insistent...
Is any member here able to give me an answer, please?

**Comment by blackears** [comment]
I just released version 1.1.3.  Still trying to figure out how to do a Maven release.  In the past I've not been able to release on Maven just because I found the process impossible to follow.

**Comment by DevCharly** [comment]
I've merged the 1.1.3 code to https://github.com/JFormDesigner/svgSalamander
and made it available on maven central:
https://github.com/JFormDesigner/svgSalamander#download

**Comment by blackears** [comment]
Thanks.

**Comment by ssenegas** [comment]
Awesome, thank you very much !
