### ISSUE TITLE
How to obtain the geometrical bounding box of an imported svg?

### ISSUE THREAD

**Issue by SaculRennorb** [blackears/svgSalamander#87]
Ive got this wonderful svg right here; [kettcards-logo.zip](https://github.com/blackears/svgSalamander/files/7651763/kettcards-logo.zip), in firefox or gimp the bounding box is as follows:
![grafik](https://user-images.githubusercontent.com/18741506/144657742-d587d559-5fa8-4da3-a68a-01f1ea202a1a.png)
However, if I try to use svgSalamander with Pdfbox the bounding box seems to be this:
![grafik](https://user-images.githubusercontent.com/18741506/144658524-4cca6955-112c-4069-8dda-d1b16abc5b4e.png)
and the does not seem to be a way to obtain the 'actual' bounding box anymore. Don't get me wrong, this _is_ the actual clip path of the svg, but I would like to obtain the geometrical bounding box of the svg defined by its width and height.

This is the code I used to render the svg with pdfbox:
```java
SVGUniverse svgUniverse = new SVGUniverse();
SVGDiagram diagram = svgUniverse.getDiagram(svgUniverse.loadSVG(file_url));

var adjusted_matrix = Matrix.getTranslateInstance(doc.getXOffset(), doc.getYOffset());
PdfBoxGraphics2D graphics = new PdfBoxGraphics2D(doc, diagram.getWidth(), diagram.getHeight());

try {
    diagram.render(graphics);
} catch (SVGException e) {
    e.printStackTrace();
} finally {
    graphics.dispose();
}

var form = graphics.getXFormObject();
form.setMatrix(adjusted_matrix.createAffineTransform());
doc.stream().drawForm(form);

//the box
PDPageContentStream stream = doc.stream();
stream.setLineWidth(1);
stream.moveTo(doc.getXOffset()                     , doc.getYOffset());
stream.lineTo(doc.getXOffset() + diagram.getWidth(), doc.getYOffset());
stream.lineTo(doc.getXOffset() + diagram.getWidth(), doc.getYOffset() + diagram.getHeight());
stream.lineTo(doc.getXOffset()                     , doc.getYOffset() + diagram.getHeight());
stream.closePath();
stream.stroke();
```
`doc` is just a class that inherits from `PDDocument` and has some extra data on it (like `getXOffset()`). There is however no change in functionality, its just for convenience. I only left it in for completeness sake, the result is the same without using any transform.

So my question is as follows, is there a way to obtain the _actual geometrical bounding box_ of the diagram, and if there is how do I do it ;).

**Comment by blackears** [comment]
If you're looking for the dimension specified in the <svg> tag, you'll need to call diagram.getRoot() and get the width and height from there.  The code you're using above uses the clipping rectangle for drawing in the viewport.

This might be something that needs to be changed.  One problem posed here is that the svg dimensions  can be specified in units other than pixels such as inches, milimeters, points, etc.  There will need to be a way to convert that to screen coordinates.

**Comment by blackears** [comment]
Closing this now.  Please reopen if you have further questions.
