### ISSUE TITLE
Wrong text align

### ISSUE THREAD

**Issue by mlaggner** [blackears/svgSalamander#90]
If you set the X/Y coordinates dynamically, the rendered images still have the old (initial) values from the SVG and not the set ones

use the SVG for example:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg"
     id="video_format"
     width="160"
     height="97"
     viewBox="-12 -5 164 97"
     version="1.1">

    <text id="text"
          y="39"
          style="font-size: 42px;
                 text-anchor: middle;
                 font-weight: bold;
                 font-style: italic;
                 display:inline;
                 stroke-width:2.85;"/>
</svg>
```

If you dynamically set the text (and coordinates), the text is always centered at 0/39:

```
protected void setText(String text, int x) {
  SVGDiagram diagram = getSvgUniverse().getDiagram(getSvgURI());
  Text textElement = (Text) diagram.getElement("text");
  if (textElement != null) {
    textElement.addAttribute("x", AnimationElement.AT_XML, String.valueOf(x));
    textElement.appendText(text);
    setFill(getHexString(UIManager.getColor("Label.foreground")), diagram.getRoot());
    textElement.rebuild();
  }
}
```

I've spotted the issue at https://github.com/blackears/svgSalamander/blob/master/svg-core/src/main/java/com/kitfox/svg/Text.java#L133 where you get the initial X value (from SVG) and afterwards read the values from the attributes, but the method ` alignSegmentsAtAnchor` is called with the initial X value (0 in out case)

**Comment by blackears** [comment]
I've updated the source and the cursor position should be calculated correctly now.  Please reopen if you're still having issues.
