### ISSUE TITLE
New release date

### ISSUE THREAD

**Issue by colbymorrison** [blackears/svgSalamander#98]
Hi,

My team's service is getting some log spam coming from SvgSalamander. It looks to be from the issue that was fixed in https://github.com/blackears/svgSalamander/pull/93. Is there a plan for a new release with this change included?

**Comment by blackears** [comment]
I've added the 1.1.4 release to the released page.  (Looks like I forgot to post it there.)  It includes the fix for #93.

**Comment by colbymorrison** [comment]
Thanks so much! Will this version be uploaded to Maven central as well?

**Comment by blackears** [comment]
It's been a while since I've tried publishing  on  maven and I've had trouble with it in the past.  I've contacted them, but it may be a few days before I'm able to publish something.

**Comment by colbymorrison** [comment]
All good. Thank you so much for your quick responses :)

**Comment by blackears** [comment]
I've spent a few hours trying to get maven to deploy and  just can't get it to work.  I've tried  publishing with maven in the past too and only ever got it to work once.  I don't think I'm going to be able to do this.  In the past, others have  published unofficial releases.  I don't think I'll be able to sink any more time into this.

**Comment by blackears** [comment]
@DevCharly has published it.  You can find it on Maven central now.  https://github.com/blackears/svgSalamander/discussions/74#discussioncomment-3817832
